name: Run linters

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/linters.yml
      - requirements-lint.txt
  pull_request:
    branches: [ master ]
jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@main
    with:
      mypy: true