name: Run tests on macos

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests-macos.yml
      - requirements-test.txt
  pull_request:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests-macos.yml
      - requirements-test.txt


jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.6.3
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.8"]'
      os: macos-latest
      pipenv: true
      pipenv-install-options: --skip-lock
