name: Run tests

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests.yml
      - requirements-test.txt
  pull_request:
    branches: [ master ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.3.1
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]'
      cover_package: src/port_for
